/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xgn_ImageUtil */

#ifndef _Included_com_xgn_ImageUtil
#define _Included_com_xgn_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xgn_ImageUtil
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;IIILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_xgn_ImageUtil_compressBitmap__Landroid_graphics_Bitmap_2IIILjava_lang_String_2Z
  (JNIEnv *, jclass, jobject, jint, jint, jint, jstring, jboolean);

/*
 * Class:     com_xgn_ImageUtil
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;ILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_xgn_ImageUtil_compressBitmap__Landroid_graphics_Bitmap_2ILjava_lang_String_2Z
  (JNIEnv *, jclass, jobject, jint, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
